// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonitorsJSON():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadMonitors():Promise<string>;

export function WriteMonitorConfig(arg1:string):Promise<string>;
