// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonitorsJSON() {
  return window['go']['main']['App']['GetMonitorsJSON']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadMonitors() {
  return window['go']['main']['App']['ReadMonitors']();
}

export function WriteMonitorConfig(arg1) {
  return window['go']['main']['App']['WriteMonitorConfig'](arg1);
}
